project:
  type: book
  output-dir: docs
  preview:
    port: 1996
    browser: false

lang: zh

book:
  title: "R语言入门"
  author: "金太阳无敌"
  date: last-modified
  date-format: "YYYY/MM/DD"
  cover-image: ./out/cover.png
  repo-url: https://github.com/kekincai/simple_and_sample_r_language
  sharing: [twitter, facebook]
  sidebar: 
    style: docked
    pinned: true
  page-navigation: true
  twitter-card:
    title: "R语言入门"
    description: "这是一本关于R语言入门的小册子。"
    card-style: summary
    image: "out/cover.png"
  open-graph:
    title: "R语言入门"
    description: "这是一本关于R语言入门的小册子。"
    image: "out/cover.png"
  chapters:
    - index.qmd
    - 01_R语言入门.qmd
    - 02_如何解题.qmd
    - 03_代码及其他.qmd
    - 04_向量及其运算.qmd
    - 05_matrix.qmd
    - 06_函数及程序流程控制.qmd
    - 07_数据导入导出.qmd
    - 08_数据可视化.qmd
    - 09_代码优化及并行.qmd
    - references.qmd
    - version.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - rn4e.scss
    # grid:
    #   sidebar-width: 375px
    # number-sections: true
    highlight-style: a11y
    html-math-method: mathjax
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    code-annotations: hover
  pdf:
    documentclass: scrreprt