---
date: "2023年 08月 20日"
date-modified: "`r format(Sys.Date(), '%Y年 %m月 %d日')`（距发布日已经过去`r as.numeric(Sys.Date() - as.Date('2023/08/20'))`天）"
title-block-banner: true
title-block-banner-color: "steelblue"
toc: true
---

# 前言 {.unnumbered}

<a name="header"></a>

这是一本关于R语言入门的小册子。
欢迎大家阅读和指正。

当前版本：{{< var version >}}

问题反馈：[{{< var email.feedback >}}](mailto:{{< var email.feedback >}}?subject=问题反馈)


## 目录

1. R语言入门
2. 如何解题
3. 代码 & 脚本 & 项目 & 编程建议
4. 向量及其运算
5. Matrix & Dataframe & List
6. 函数 & 程序流程控制
7. 数据导入 &导出
8. 数据可视化
9. 代码优化 & 并行

## 写作目的
R语言是一门面向数据分析，统计建模的编程语言。也是我第一门真正掌握的语言。
这本小册子不光是一本编程语言的教程，也记载着我多年工作经历和收获。
我想借着写作这本书总结反思自己过去的经验，也希望能够梳理过去关于R语言不准确不全面的认识。
增强自己对R语言的理解，也希望能够帮助到更多的人。

本书基本上是介绍base R^[RStudio公司开发跟维护的包是目前大家更为普遍的选择。但是本书还是认为掌握base R是我们未来工作和研究的基础。]的用法，在可重复性研究上，使用基础的R语法会让后来人很方便的复现当时的结果。

## 谁适合阅读本书

### 本书适合谁？
本书主要面向以下几类读者：

(@) **非计算机专业研究人员**：如果你是一名专业研究人员，但没有编程背景，本书将为你提供一个简单易懂的编程入门指南。

(@) **数据分析新手**：对于刚开始接触数据分析的人，本书将教你如何使用R语言进行数据处理、分析和可视化。

(@) **计算机专业跨行人员**：如果你是一名程序员，本书将为你提供一个简单易懂的数据分析入门指南。

### 本书不适合谁？

- 如果你已经是R语言的高级用户，那么本书可能不会提供太多新的信息。

    推荐阅读Hadley Wickham的新书 [《R for Data Science》](https://r4ds.hadley.nz/){target="_blank"}。

    如果你想了解更多的R语言高级技术，推荐阅读 [《Advanced R》](https://adv-r.hadley.nz/){target="_blank"}。

    如果日语水平可以的话，推荐阅读 [《私たちのR》](https://www.jaysong.net/RBook/){target="_blank"}。

    最新最准确最全面的R语言资料，推荐访问R语言官方网站 [R Project](https://www.r-project.org/){target="_blank"}。

### 预备知识

读者最好具备基础的数学和统计学知识，不过本书也会尽量用简单明了的方式解释所有概念。

## 本书代码执行环境
```{r, echo=FALSE}
sys.info <- Sys.info()
message(
    "    machine  : ", sys.info["machine"], "\n",
    "    platform : ", R.version$platform, "\n",
    "    version  : ", R.version$version.string, "\n",
    "               ", R.version$nickname
)
```

[⇧](#header)